### ISSUE TITLE
Host pattern error with tags

### ISSUE THREAD

**Issue by debjit-das** [phamthuonghai/ansible-spark-ec2#1]
First of all, many thanks for writing the solo playbook available on the net for building up a detailed cluster on EC2.

However, after a few modification of my own to the variables, I am unable to proceed through the steps after the instance creation.

Looks like the tasks are not able to get hold of the created instances by the hostname provided.
"[WARNING]: Could not match supplied host pattern, ignoring: tag_ds_tech_spark"
 
Any help is appreciated.

**Comment by phamthuonghai** [comment]
Hi @debjit-das,

Can you try to run the creating task and the rest separately?

By moving these lines from `ds_platform.yaml` to something like `ds_create_platform.yaml`
```
- name: Create instances on Amazon EC2
  hosts: localhost
  roles:
  - create_spark_cluster
```
Then run `ds_create_platform.yaml`, wait a moment, run `ds_platform.yaml`.

I guess after creating the machines on AWS, it will take a while for initialization.

**Comment by debjit-das** [comment]
Hi phamthuonghai,

Thank you so much for the quick response. I tried with separating the creation process and inserted a pause too. But I guess it is unable to pick hostnames when addressed with the respective tag names. 

As a workaround, I tried with assigning the instances to groups in the create_spark_cluster task and voila, it worked like a charm.

```
- name: Add node to slave_private group
      add_host:
        groupname: "slave_private"
        hostname: "{{ spark_slave.instances[0].private_ip }}"
```
Did the same for master and for public ip too. Then passed the groups as hostnames for the tasks.

Hope this can help someone facing this issue.
